### ISSUE TITLE
ReadContainer better name?

### ISSUE THREAD

**Issue by boukew99** [Wcubed/horizontal_flow_container#2]
The container acts just as if you are writing/reading, so perhaps that would be a more descriptive name?

**Comment by Wcubed** [comment]
Good suggestion. When figuring out what to call the thing, I think I took inspiration from some other UI libraries, though I can't remember where I've seen the term before.
Read container is indeed more descriptive (although one might confuse it as a container that reads from somewhere, instead of you reading it). I'll see if I can change it next time I fix some bug / add a feature.

**Comment by boukew99** [comment]
Altough if you ever make an VFlowContainer then HFlowContainer makes more sense.

**Comment by rgson** [comment]
FWIW, I think this change should not be implemented.

I don't see any problem with the current name; it's indeed consistent with major UI libraries like [Java Swing](https://docs.oracle.com/javase/tutorial/uiswing/layout/flow.html), [Windows Forms](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.flowlayoutpanel?view=net-5.0), [GTK](https://developer.gnome.org/gtk3/stable/GtkFlowBox.html) and [Qt](https://doc.qt.io/qt-5/qtwidgets-layouts-flowlayout-example.html). On the other hand, I've never heard "read" used in such a way and would never have found this project by that name.

Besides, changing the name is a breaking change that's possibly quite inconvenient to your users.

**Comment by Wcubed** [comment]
That's a very good point, changing the name would break basically everything using it. Also, thanks for linking to the ui libraries, I now remember it was Qt and GTK where I saw the term used before :grin:
I'll close this one :+1:

(And indeed, the plan is to also have a VFlowContainer. I don't know whether renaming the addon itself breaks stuff, but if it doesn't i'll add it to this one.)
